CREATE TABLE TLM_NAME_DIM (
    ID BIGINT PRIMARY KEY,
    TLM_NAME VARCHAR(128) NOT NULL
);

CREATE TABLE TLM_DATA (
    TLM_NAME_ID BIGINT NOT NULL,
    TLM_VALUE DOUBLE,
    CATEGORY VARCHAR(32) NOT NULL,
    TLM_TIME TIMESTAMP NOT NULL,
    EXECUTION_ID BIGINT,
    CONSTRAINT FK_TLM_DATA_NAME FOREIGN KEY (TLM_NAME_ID) REFERENCES TLM_NAME_DIM (ID)
);

CREATE TABLE RESET_DATA (
    TLM_NAME_ID BIGINT NOT NULL,
    TLM_VALUE DOUBLE,
    CATEGORY VARCHAR(32) NOT NULL,
    INPUT_FILE_NAME VARCHAR(256) NOT NULL,
    SEGMENT_INDEX INT NOT NULL,
    CONSTRAINT FK_RESET_DATA_NAME FOREIGN KEY (TLM_NAME_ID) REFERENCES TLM_NAME_DIM (ID)
);
